language: groovy
jdk:
  - openjdk8

notifications:
  email:
    on_success: never
    on_failure: always

jobs:
  include:
  - stage: Tests
    name: "unitTests"
    script:
    - ./gradlew clean
    - ./gradlew test