#!groovy

node ('master'){

  try{

    stage('SCM'){

        checkout([
            $class: 'GitSCM',
            branches: [[name: '*/develop']],
            doGenerateSubmoduleConfigurations: false,
            extensions: [],
            submoduleCfg: [],
            userRemoteConfigs: [[url: 'https://github.com/iteratec/OsmDetailAnalysis.git']]
        ])

    }

    stage('Copy compose file to host'){
        sh './scripts/ci/deploy/copy_compose_file_to_host.sh'
    }

    withCredentials([
        [
            $class: 'UsernamePasswordMultiBinding',
            credentialsId: 'OSMDA_API_KEY_PROD_ITERATEC',
            passwordVariable: 'OSMDA_API_KEY_PROD_ITERATEC',
            usernameVariable: 'OSMDA_API_KEY_PROD_ITERATEC_VARNAME'
        ],
        [
            $class: 'UsernamePasswordMultiBinding',
            credentialsId: 'OSMDA_API_KEY_DEV_ITERATEC',
            passwordVariable: 'OSMDA_API_KEY_DEV_ITERATEC',
            usernameVariable: 'OSMDA_API_KEY_DEV_ITERATEC_VARNAME'
        ],
        [
            $class: 'UsernamePasswordMultiBinding',
            credentialsId: 'OSMDA_API_KEY_OTTO',
            passwordVariable: 'OSMDA_API_KEY_OTTO',
            usernameVariable: 'OSMDA_API_KEY_OTTO_VARNAME'
        ],
        [
            $class: 'UsernamePasswordMultiBinding',
            credentialsId: 'seu_jenkins_iteratec_at_osm_hh_iteratec_de',
            passwordVariable: 'seu_jenkins_iteratec_at_osm_hh_iteratec_de',
            usernameVariable: 'seu_jenkins_iteratec_at_osm_hh_iteratec_de_VARNAME'
        ],
    ]){

        stage('prepare env file for compose on host'){

            sh './scripts/ci/deploy/prepare_compose_env_file.sh'

        }
        stage('run compose deployment on host'){

            sh './scripts/ci/deploy/run_compose_deployment.sh'

        }

    }


  } catch(e) {

    currentBuild.result = "FAILED"
    //notifyFailed()
    throw e

  }

}

def notifyFailed() {
  def subject = "${currentBuild.result}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
  def body = """<p>STARTED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
  <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>"""

  mail(
   body: body,
   subject: subject,
   to: 'nils.kuhn@iteratec.de'
  )
}
