#!groovy

node ('master'){

  try{

    stage('SCM'){

        checkout([
            $class: 'GitSCM',
            branches: [[name: '*/develop']],
            doGenerateSubmoduleConfigurations: false,
            extensions: [],
            submoduleCfg: [],
            userRemoteConfigs: [[url: 'https://github.com/iteratec/OsmDetailAnalysis.git']]
        ])

    }

    withCredentials([
        [
            $class: 'UsernamePasswordMultiBinding',
            credentialsId: 'SEU_JENKINS_ITERATEC_AT_OSM_HOSTS',
            passwordVariable: 'SEU_JENKINS_ITERATEC_AT_OSM_HOSTS_PASSWORD',
            usernameVariable: 'SEU_JENKINS_ITERATEC_AT_OSM_HOSTS_USERNAME'
        ],
        [
            $class: 'StringBinding',
            credentialsId: 'OSMDA_API_KEY_PROD_ITERATEC',
            variable: 'OSMDA_API_KEY_PROD_ITERATEC'
        ],
        [
            $class: 'StringBinding',
            credentialsId: 'OSMDA_API_KEY_DEV_ITERATEC',
            variable: 'OSMDA_API_KEY_DEV_ITERATEC'
        ],
        [
            $class: 'StringBinding',
            credentialsId: 'OSMDA_API_KEY_OTTO',
            variable: 'OSMDA_API_KEY_OTTO'
        ],
        [
            $class: 'StringBinding',
            credentialsId: 'OSMDA_API_KEY_DEMO',
            variable: 'OSMDA_API_KEY_DEMO'
        ],
        [
            $class: 'StringBinding',
            credentialsId: 'OSMDA_API_KEY_LHT',
            variable: 'OSMDA_API_KEY_LHT'
        ]
    ]){

        stage('Copy compose file to host.'){
            sh './scripts/ci/deploy/copy_compose_file_to_host.sh'
        }

        stage('Prepare env file for compose on host.'){
            sh './scripts/ci/deploy/prepare_compose_env_file.sh'
        }

        stage('Run compose deployment on host.'){
            sh './scripts/ci/deploy/run_compose_deployment.sh'
        }

    }


  } catch(e) {

    currentBuild.result = "FAILED"
    //notifyFailed()
    throw e

  }

}

def notifyFailed() {
  def subject = "${currentBuild.result}: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'"
  def body = """<p>STARTED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
  <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>"""

  mail(
   body: body,
   subject: subject,
   to: 'nils.kuhn@iteratec.de'
  )
}
