version: '2'

services:

  osm_da:
    image: iteratec/osm-detail-analysis:latest
    env_file:
       - .env-osmda-behind-reverse-proxy

  osm_mongodb:
    image:  mongo:3.2
    volumes:
      - osm_mongodb_data:/data/db

networks:
  default:
    external:
      name: reverse_proxy_net

volumes:
  osm_mongodb_data:
    driver: local