osm_da:
  image: iteratec/osm-detail-analysis
  entrypoint: dockerize -wait tcp://osm_mongodb:27017 -timeout 240s -stdout ${OSM_DA_HOME}/logs/OsmDetailAnalysisDetails.log -stderr ${OSM_DA_HOME}/logs/OsmDetailAnalysis.log /entrypoint.sh
  ports:
   - "${PUBLIC_PORT}:8081"
  links:
   - osm_mongodb
  environment:
    - MONGODB_HOST
    - INITIAL_API_KEY
    - INITIAL_OSM_URL
    - PUBLIC_PORT
    - OSM_JVM_XMS
    - OSM_JVM_XMX

osm_mongodb:
  image:  mongo:3.2